<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>EventFeed</AssemblyName>
    <FileAlignment>512</FileAlignment>
    <Deterministic>true</Deterministic>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <Import Project="..\Environment.props" Condition="Exists('..\Environment.props')" />

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
    <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.1" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="assembly_valheim" Publicize="true">
      <HintPath>$(VALHEIM_DEDI_INSTALL)\Data\Managed\assembly_valheim.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(VALHEIM_DEDI_INSTALL)\Data\Managed\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(VALHEIM_DEDI_INSTALL)\Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(VALHEIM_DEDI_INSTALL)\BepInEx\core\0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>$(VALHEIM_DEDI_INSTALL)\BepInEx\core\BepInEx.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>
